# Generated by Django 5.0.6 on 2024-06-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('chat', '0002_alter_chat_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chat',
            field=models.ManyToManyField(related_name='chat_rooms', to='chat.chat', verbose_name='Чаты'),
        ),
    ]
