# Generated by Django 5.0.6 on 2024-06-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='name',
        ),
        migrations.AddField(
            model_name='chat',
            name='title',
            field=models.CharField(default=1, max_length=200, verbose_name='Название чата'),
            preserve_default=False,
        ),
    ]
