# Generated by Django 5.0.6 on 2024-06-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_chat_name_chat_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='messages',
            field=models.ManyToManyField(related_name='messages', to='chat.messages'),
        ),
    ]
