# Generated by Django 5.0.6 on 2024-06-26 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_remove_messages_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='chat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='chat.chat'),
            preserve_default=False,
        ),
    ]
